Add step in prepare-command to check the command starts with `!test`

diff --git a/.github/workflows/config-comment-test.yml b/.github/workflows/config-comment-test.yml
--- a/.github/workflows/config-comment-test.yml
+++ b/.github/workflows/config-comment-test.yml
@@ -119,7 +119,16 @@ jobs:
           fetch-depth: 0
           fetch-tags: true
 
-      - name: Get test type
+      - name: Verify !test
+        run: |
+          if [[ "${{ startsWith(github.event.comment.body, '!test') }}" == "true" ]]; then
+            echo 'Command starts with !test'
+          else
+            echo "::error::Usage: ${{ env.USAGE }}"
+            echo "::error::Command must start with !test to invoke model-config-tests' config-comment-test.yml."
+            exit 1
+
+      - name: Get !test type
         id: test
         run: |
           command="${{ github.event.comment.body }}"
